parameters:
#    musicatoulouse_user.example.class: MusicaToulouse\UserBundle\Example

services:
#    musicatoulouse_user.example:
#        class: %musicatoulouse_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
