parameters:
    user_bundle.handler.login_success_handler.class: MusicaToulouse\UserBundle\Handler\LoginSuccessHandler
    user_bundle.handler.logout_success_handler.class: MusicaToulouse\UserBundle\Handler\LogoutSuccessHandler
    
services:
    user_bundle.handler.login_success_handler:
        class:  %user_bundle.handler.login_success_handler.class%
        arguments:  [@router, @security.context]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
    user_bundle.handler.logout_success_handler:
        class:  %user_bundle.handler.logout_success_handler.class%
        arguments:  [@router]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    musicatoulouse.twig.datetime_extension:
        class: MusicaToulouse\WebsiteBundle\Twig\DateTimeExtension
        tags:
            - { name: twig.extension }